# Numpy

In [56]:
import numpy as np 

In [57]:
arr_1d = np.array([1,2,3])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,6,7],[1,2,3,4]])
print("2D array:",arr_2d)

1D array: [1 2 3]
2D array: [[1 2 6 7]
 [1 2 3 4]]


## List vs Numpy array

In [ ]:
py_list = [1,2,3]
print("Python list multiplication:",py_list*2)

np_array = np.array([1,2,3])
print("Python array multiplicaton:",np_array*2) #element wise multiplication
 

Python list multiplication: [1, 2, 3, 1, 2, 3]
Python array multiplicaton: [2 4 6]


In [59]:
import time
start = time.time()
py_list= [2,3,4]
py_list = [i*2 for i in range(1000000)]
print("\n List operatin time: ",time.time()-start)

start = time.time()
#np_array = np.array([2,3,4])
np_array = np.arange(1000000)*2
print("\nNumpy operation time: ",time.time()-start)



 List operatin time:  0.05955171585083008

Numpy operation time:  0.004376649856567383


## creating array from scratch

In [60]:
zeros = np.zeros((3,4))
print("Zeors array:\n",zeros)

ones = np.ones((3,4))
print("Ones array: \n",ones)

full = np.full((2,2),7)
print("Full array with value 7: \n",full)

random = np.random.random((2,4))
print("Random array: \n",random)

sequence = np.arange(0,10,2)
print("Sequence array: ",sequence)

Zeors array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array with value 7: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.88755636 0.60442354 0.74723842 0.1001085 ]
 [0.71873525 0.41255165 0.91314051 0.75635682]]
Sequence array:  [0 2 4 6 8]


### Vector , Matrix and Tensor

In [61]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2],[3,4]])
print("Matrix: \n",matrix)

#tensor means more dimension
tensor = np.array([[[1,2],[3,4]],
[[5,6],[7,8]]])
print("Tensor: \n",tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2]
 [3 4]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

In [62]:
arr = np.array([[1,2,3],[4,5,3]])
#shape give (row,column)
print("Shape :",arr.shape)

print("Dimenson: ",arr.ndim)

print("Size: ",arr.size)
print("DataType: ",arr.dtype)

Shape : (2, 3)
Dimenson:  2
Size:  6
DataType:  int64


Array Reshaping

In [63]:
arr = np.arange(8)
print("Original array:",arr)

#reshape
reshaped = arr.reshape((2,4))
print("Reshaped array: \n",reshaped)

flatend = reshaped.flatten()
print("Flatend array : \n",flatend)


#ravel (return view , instead of copy)
reveled = reshaped.ravel()
print("Ravel array:\n",reveled)

#transpose 
transpose = reshaped.T
print("Transposed array: \n",transpose)

reveled = transpose.ravel()
print("Transpose Ravel: \n",reveled)

Original array: [0 1 2 3 4 5 6 7]
Reshaped array: 
 [[0 1 2 3]
 [4 5 6 7]]
Flatend array : 
 [0 1 2 3 4 5 6 7]
Ravel array:
 [0 1 2 3 4 5 6 7]
Transposed array: 
 [[0 4]
 [1 5]
 [2 6]
 [3 7]]
Transpose Ravel: 
 [0 4 1 5 2 6 3 7]


# Phase 2 for Numpy

## Numpy array operation

In [64]:
import numpy as np

In [65]:
arr = np.array([1,2,3,4,5,6,7,8])
print("Basic slicing ",arr[2:7])
print("Slicing using step ",arr[1:8:4])
print("negative indexing: ",arr[-3])

Basic slicing  [3 4 5 6 7]
Slicing using step  [2 6]
negative indexing:  6


In [66]:
arr_2d = np.array([[1,12,3],[1,5,6],[4,7,8]])
print("Specific element: ",arr_2d[2][2])
print("Entire row: ",arr_2d[1])
print("Entire column: ",arr_2d[:,2])

array = arr_2d[:,1]
print("2nd Column:",array)

print("Sorted 2nd column: ", np.sort(array))


Specific element:  8
Entire row:  [1 5 6]
Entire column:  [3 6 8]
2nd Column: [12  5  7]
Sorted 2nd column:  [ 5  7 12]


## sorting 

In [67]:
unsorted = np.array([3,1,4,2,6,5,8])
print("Sorted array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[2000,99],[4,6]])
print("Sorted 2d array by column: ",np.sort(arr_2d_unsorted, axis = 0))
print("Sorted 2d array by row: ",np.sort(arr_2d_unsorted,axis=1))

Sorted array:  [1 2 3 4 5 6 8]
Sorted 2d array by column:  [[   3    1]
 [   4    6]
 [2000   99]]
Sorted 2d array by row:  [[   1    3]
 [  99 2000]
 [   4    6]]


## filter

In [68]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers%2==0]
print("Even numbers:",even_number)



Even numbers: [2 4 6 8]


## Filter with mask

In [69]:
mask = numbers > 5
print("Numbers greater than 5: ",numbers[mask])

Numbers greater than 5:  [6 7 8 9]


## Fancy indexing vs np.where

In [70]:
indices = [0,2,4]
print("Numbers with idices given:\n ",numbers[indices])

where_result = np.where(numbers>7)
print(where_result)
print("Np Where: ",numbers[where_result])

Numbers with idices given:
  [1 3 5]
(array([7, 8]),)
Np Where:  [8 9]


In [71]:
condition_array = np.where(numbers>5,"True1", "False0")
print(condition_array)


condition_array = np.where(numbers>4)
print(condition_array)

['False0' 'False0' 'False0' 'False0' 'False0' 'True1' 'True1' 'True1'
 'True1']
(array([4, 5, 6, 7, 8]),)


## Adding and removing data

In [72]:
arr1 = np.array([1,23,4,3,4])
arr2 = np.array([2,5,6,7,4])

arr3 = arr1 + arr2
print(arr3)

combinedArray = np.concatenate((arr1,arr2))
print(combinedArray)

[ 3 28 10 10  8]
[ 1 23  4  3  4  2  5  6  7  4]


### Array compatibility

In [73]:
a = np.array([2,3,4,2])
b = np.array([3,4,2,3])
c = np.array([[2,3,2,1],[4,53,2,5]])

print("Compatibility of a nd b : ",a.shape == b.shape)
print("Compatibility of c nd b : ",c.shape == b.shape)

Compatibility of a nd b :  True
Compatibility of c nd b :  False


In [74]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_column = np.array([[4],[5]])
with_new_column = np.hstack((original,new_column))
print("\n\nwith new column:\n",with_new_column)

arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2) #return array not deleted element
print("delete array element:",deleted)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


with new column:
 [[1 2 4]
 [3 4 5]]
delete array element: [1 2 4 5]
